@startuml Arduino Nano Sistema de Riego

' Definición de símbolos
skinparam defaultFontName Arial
skinparam titleFontSize 15
skinparam diagramPadding 10
skinparam conditionDiamondBackgroundColor #A9DCDF
skinparam conditionDiamondBorderColor #34495E
skinparam activityBackgroundColor #E9EBF0
skinparam activityBorderColor #34495E

' Título
title Diagrama de Proceso - Arduino

' Definición de nodos y flujo

start
repeat
    :Leer Humedad;
    :Leer Luz 1;
    :Leer Luz 2;
    :Enviar Humedad por Bluetooth;
    :Enviar Luz 1 por Bluetooth;
    :Enviar Luz 2 por Bluetooth;
    :Ajustar el tiempo si es necesario
    :Recibir mensaje Bluetooth para configurar el riego rutinario
    if (Es Hora de Riego?) then (Sí)
        if (Humedad en Rango Permitido?) then (Sí)
            :Activar Sistema de Riego;
        else (No)
            :Simular Sistema de Riego;
        endif
        :Actualizar Último Tiempo de Riego;
    else (No)
        if (Humedad Baja?) then (Sí)
            :Enviar Mensaje Bluetooth "¡ALERTA! ¡Humedad baja detectada!";
            :Calcular Tiempo Restante Para Próximo Riego;
            if (Tiempo Restante > Duración del Riego) then (Sí)
                :Activar Sistema de Riego;
            endif

        endif
    endif
repeat while (true)


stop

@enduml
